### ISSUE TITLE
Incorrect spelling of "Repository"

### ISSUE THREAD

**Issue by ralismark** [V-Wong/Portfolio#3]
You write "Respository" sometimes, which is not the correct spelling.

**Comment by lukefisklennon** [comment]
lmoa

**Comment by sadsunshower** [comment]
Either spelling is actually considered okay under the new draft proposal for English 1.1, in fact there were plans to make "Repository" deprecated. But I agree you should aim for consistency in your codebase, either have full English 1.1 compliance, or full legacy English 1.0 please.

**Comment by vwcwong** [comment]
Fixed in commit [2727c509ffc518c4a2268458634901c7d1dae452](https://github.com/V-Wong/Portfolio/commit/2727c509ffc518c4a2268458634901c7d1dae452)
